version: '3'
services:
  ticketing-BE:
    container_name: ticketing-BE
    image: rdas/bus-ticketing-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - my-network
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network
  
networks:
  my-network:
      driver: bridge